import ResponsiveAppBar from "@/components/navbar";
import AppTheme from "@/components/shared-theme/AppTheme";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import CssBaseline from "@mui/material/CssBaseline";

export const metadata = {
	title: "Suprathon Submission",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
				<AppRouterCacheProvider options={{ enableCssLayer: true }}>
					<AppTheme>
						<CssBaseline />
						<ResponsiveAppBar />
						{children}
					</AppTheme>
				</AppRouterCacheProvider>
			</body>
		</html>
	);
}
